package org.isswqm.notewise.config;
public enum Statements {
    WAITING,
    WAITING_FOR_REMIND_TEXT_INPUT,
    WAITING_FOR_REMIND_DATE_INPUT,
    REMIND_IS_SAVING,
    WAITING_FOR_NOTE_TEXT_INPUT,
    NOTE_IS_SAVING,
    WAITING_FOR_NOTES_VIEW,

    WAITING_FOR_DELETE_NOTE,
    NOTE_IS_DELETED,
    WAITING_FOR_EDITING_NOTE_DATE_INPUT,
    WAITING_FOR_EDITING_NOTE_TEXT_INPUT,
    NOTE_IS_EDITED,

    WAITING_FOR_SEARCH_NOTE_DATE_INPUT,

    NoteFound;
}
