package org.isswqm.notewise.config;
public enum Statements {
    WAITING,
    WAITING_FOR_ADD_REMIND_TEXT_INPUT,
    WAITING_FOR_ADD_REMIND_DATE_INPUT,
    REMIND_SAVING,
    WAITING_FOR_NOTE_TEXT_INPUT,
    NOTE_SAVING,
    WAITING_FOR_VIEW_NOTES,
    WAITING_FOR_DELETE_NOTE,
    NOTE_DELETED,
    WAITING_FOR_EDITING_NOTE_DATE_INPUT,
    WAITING_FOR_EDITING_NOTE_TEXT_INPUT,
    NOTE_EDITED,
    WAITING_FOR_SEARCH_NOTE_DATE_INPUT,
    NOTE_FOUND,
    WAITING_FOR_VIEW_REMIND,
    WAITING_FOR_DELETE_REMIND,
    REMIND_DELETED;
}
